import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;
  AppLocalizations(this.locale);

  static AppLocalizations? of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations);
  }

  static const _localizedValues = <String, Map<String, String>>{
    'en': {
      'profile': 'Profile',
      'status': 'Status',
      'active': 'Active ✅',
      'pending': 'Pending ⏳',
      'specialization': 'Specialization',
      'clinic_address': 'Clinic Address',
      'clinic_phone': 'Clinic Phone',
      'verification_status': 'Verification Status',
      'edit': 'Edit',
      'delete_account': 'Delete Account',
      'confirm_delete': 'Confirm Delete',
      'delete_warning':
          'Are you sure you want to delete your account? This action cannot be undone.',
      'cancel': 'Cancel',
      'delete': 'Delete',
      'error': 'Error',
      'edit_profile': 'Edit Profile',
      'name': 'Name',
      'email': 'Email',
      'save_changes': 'Save Changes',
      "home": "Home",
      "health_records": "Health Records",
      "medicines": "Medicines",
      "community": "Community",
      "smart_assistant": "Smart Assistant",
      "records": "Records",
      "change_language": "Change Language",
      "logout": "Logout",
      "logout_confirmation": "Are you sure you want to logout?",
      "confirm": "Confirm",
      "unknown_user": "Unknown User",
      "no_email": "No email",
      'add_medicine': 'Add Medicine',
      'medicine_name': 'Medicine Name',
      'example_amoxicillin': 'Example: Amoxicillin',
      'dosage': 'Dosage',
      'example_500mg': 'Example: 500mg',
      'daily_usage_times': 'Daily Usage Times',
      'times': 'Times',
      'first_dose_time': 'First Dose Time',
      'start_date': 'Start Date',
      'usage_days_count': 'Usage Days Count',
      'day': 'Day',
      'save_medicine': 'Save Medicine',
      'select_time': 'Select Time',
      'select_date': 'Select Date',
      'select_time_date': 'Please select time and date',
      'medicine_saved_success': 'Medicine saved successfully',
      'save_medicine_failed': 'Failed to save medicine',
      'medicine_added_to_list': 'Medicine added to list',
      'required': 'Required',
      'health_value': 'Health Value',
      'patient_records': 'Patient Records',
      'failed_load_patient_data': 'Failed to load patient data',
      'failed_load_health_data': 'Failed to load health data',
      'data_updated_success': 'Data updated successfully',
      'failed_update_data': 'Failed to update data',
      'try_again': 'Try Again',
      'no_patient_data': 'No patient data available',
      'reload': 'Reload',
      'no_data_today': 'No data available for today',
      'entered_at': 'Entered at',
      'failed_delete_value': 'Failed to delete value',
      'medications_list': 'Medications List',
      'todays_medications': "Today's Medications",
      'health_status': 'Health Status',
      'blood_pressure': 'Blood Pressure',
      'blood_sugar': 'Blood Sugar',
      'recent_activity': 'Recent Activity',
      'last_measurement': 'Last Measurement',
      'normal': 'Normal',
      'measured_on': 'Measured on',
      'quick_actions': 'Quick Actions',
      'add_blood_pressure': 'Add BP',
      'add_blood_sugar': 'Add Sugar',
      'type_message_hint': 'Type your message...',
      'typing': 'Typing...',
      'error_sending_message':
          'Sorry, I encountered an error. Please try again.',
      'mmhg': 'mmHg',
      'systolic': 'Systolic',
      'diastolic': 'Diastolic',
      'low': 'Low',
      'elevated': 'Elevated',
      'high': 'High',
      'very_high': 'Very High',
      'pressure_saved_success': 'Blood pressure saved successfully',
      'failed_save_measurement': 'Failed to save measurement',
      'no_medications': 'No medication today',
      'filtered_list': 'Filtered List',
      'selected_date': 'Selected Date',
      'total_reminders': 'Total Reminders',
      'filtered_reminders': 'Filtered Reminders',
      'no_reminders_for_date': 'No reminders for selected date',
      'reminder_id': 'Reminder ID',
      'time': 'Time',
      'no_medications_for_date': 'No medications for selected date',
      'change_date': 'Change date',
      'dose_times': 'Dose Times:',
      'blood_sugar_value': 'Blood sugar value',
      'mgdl': 'mg/dL',
      'fasting': 'Fasting',
      'prediabetes': 'Prediabetes',
      'slightly_high': 'Slightly high',
      'unknown': 'Unknown',
      'sugar_saved_success': 'Sugar measurement saved successfully',
    },
    'ar': {
      'profile': 'الملف الشخصي',
      'status': 'الحالة',
      'active': 'مفعل ✅',
      'pending': 'بانتظار التفعيل ⏳',
      'specialization': 'التخصص',
      'clinic_address': 'عنوان العيادة',
      'clinic_phone': 'هاتف العيادة',
      'verification_status': 'حالة التحقق',
      'edit': 'تعديل',
      'delete_account': 'حذف الحساب',
      'confirm_delete': 'تأكيد الحذف',
      'delete_warning': 'هل أنت متأكد أنك تريد حذف حسابك؟ لا يمكن التراجع.',
      'cancel': 'إلغاء',
      'delete': 'حذف',
      'error': 'حدث خطأ',
      'edit_profile': 'تعديل الملف الشخصي',
      'name': 'الاسم',
      'email': 'البريد الإلكتروني',
      'save_changes': 'حفظ التغييرات',
      "home": "الرئيسية",
      "health_records": "السجلات الصحية",
      "medicines": "الأدوية",
      "community": "المجتمع",
      "smart_assistant": "المساعد الذكي",
      "records": "السجلات",
      "change_language": "تغيير اللغة",
      "logout": "تسجيل الخروج",
      "logout_confirmation": "هل أنت متأكد من أنك تريد تسجيل الخروج؟",
      "confirm": "تأكيد",
      "unknown_user": "مستخدم غير معروف",
      "no_email": "لا يوجد بريد إلكتروني",
      'add_medicine': 'إضافة دواء',
      'medicine_name': 'اسم الدواء',
      'example_amoxicillin': 'مثال: أموكسيسيلين',
      'dosage': 'الجرعة',
      'example_500mg': 'مثال: 500mg',
      'daily_usage_times': 'عدد مرات الاستخدام يومياً',
      'times': 'مرات',
      'first_dose_time': 'وقت الجرعة الأولى',
      'start_date': 'تاريخ البدء',
      'usage_days_count': 'عدد أيام الاستخدام',
      'day': 'يوم',
      'save_medicine': 'حفظ الدواء',
      'select_time': 'اختر الوقت',
      'select_date': 'اختر التاريخ',
      'select_time_date': 'يرجى اختيار الوقت والتاريخ',
      'medicine_saved_success': 'تم حفظ الدواء بنجاح',
      'save_medicine_failed': 'فشل حفظ الدواء',
      'medicine_added_to_list': 'تمت إضافة الدواء إلى القائمة',
      'required': 'مطلوب',
      'health_value': 'القيم الصحية',
      'patient_records': 'سجلات المريض',
      'failed_load_patient_data': 'فشل في تحميل بيانات المريض',
      'failed_load_health_data': 'فشل في تحميل البيانات الصحية',
      'data_updated_success': 'تم تحديث البيانات بنجاح',
      'failed_update_data': 'فشل في تحديث البيانات',
      'try_again': 'إعادة المحاولة',
      'no_patient_data': 'لا توجد بيانات للمريض',
      'reload': 'إعادة تحميل',
      'no_data_today': 'لا توجد بيانات في هذا اليوم',
      'entered_at': 'تم الإدخال:',
      'failed_delete_value': 'فشل في حذف القيمة',
      'medications_list': 'قائمة الأدوية',
      'todays_medications': 'أدوية اليوم',
      'health_status': 'الحالة الصحية',
      'blood_pressure': 'ضغط الدم',
      'blood_sugar': 'سكر الدم',
      'recent_activity': 'النشاط الأخير',
      'last_measurement': 'آخر قياس',
      'normal': 'طبيعي',
      'measured_on': 'تم القياس في',
      'quick_actions': 'إجراءات سريعة',
      'add_blood_pressure': 'إضافة ضغط',
      'add_blood_sugar': 'إضافة سكر',
      'type_message_hint': 'اكتب رسالتك...',
      'typing': 'يكتب الآن...',
      'error_sending_message': 'عذراً، حدث خطأ. يرجى المحاولة مرة أخرى.',
      'mmhg': 'ملم زئبق',
      'systolic': 'الانقباضي',
      'diastolic': 'الانبساطي',
      'low': 'منخفض',
      'elevated': 'مرتفع قليلاً',
      'high': 'مرتفع',
      'very_high': 'مرتفع جداً',
      'pressure_saved_success': 'تم حفظ قياس الضغط بنجاح',
      'failed_save_measurement': 'فشل في حفظ القياس',
      'no_medications': 'لا يوجد أدوية اليوم',
      'filtered_list': 'القائمة بعد الفلترة',
      'selected_date': 'التاريخ المحدد',
      'total_reminders': 'عدد جميع الـ reminders',
      'filtered_reminders': 'عدد الـ reminders بعد الفلترة',
      'no_reminders_for_date': 'لا توجد reminders للتاريخ المحدد',
      'reminder_id': 'Reminder ID',
      'time': 'الوقت',
      'no_medications_for_date': 'لا توجد أدوية للتاريخ المحدد',
      'change_date': 'تغيير التاريخ',
      'dose_times': 'مواعيد الجرعات:',
      'blood_sugar_value': 'قيمة سكر الدم',
      'mgdl': 'ملغم/ديسيلتر',
      'fasting': 'صائم',
      'prediabetes': 'ما قبل السكري',
      'slightly_high': 'مرتفع قليلاً',
      'unknown': 'غير معروف',
      'sugar_saved_success': 'تم حفظ قياس السكر بنجاح',
    },
  };

  String get(String key) {
    return _localizedValues[locale.languageCode]?[key] ??
        _localizedValues['en']![key]!;
  }
}

class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['en', 'ar'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(AppLocalizationsDelegate old) => false;
}
