import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;
  AppLocalizations(this.locale);

  static AppLocalizations? of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations);
  }

  static const _localizedValues = <String, Map<String, String>>{
    'en': {
      'profile': 'Profile',
      'status': 'Status',
      'active': 'Active ✅',
      'pending': 'Pending ⏳',
      'specialization': 'Specialization',
      'clinic_address': 'Clinic Address',
      'clinic_phone': 'Clinic Phone',
      'verification_status': 'Verification Status',
      'edit': 'Edit',
      'delete_account': 'Delete Account',
      'confirm_delete': 'Confirm Delete',
      'delete_warning':
          'Are you sure you want to delete your account? This action cannot be undone.',
      'cancel': 'Cancel',
      'delete': 'Delete',
      'error': 'Error',
      'edit_profile': 'Edit Profile',
      'name': 'Name',
      'email': 'Email',
      'save_changes': 'Save Changes',
      "home": "Home",
      "health_records": "Health Records",
      "medicines": "Medicines",
      "community": "Community",
      "smart_assistant": "Smart Assistant",
      "records": "Records",
      "change_language": "Change Language",
      "logout": "Logout",
      "logout_confirmation": "Are you sure you want to logout?",
      "confirm": "Confirm",
      "unknown_user": "Unknown User",
      "no_email": "No email",
      'add_medicine': 'Add Medicine',
      'medicine_name': 'Medicine Name',
      'example_amoxicillin': 'Example: Amoxicillin',
      'dosage': 'Dosage',
      'example_500mg': 'Example: 500mg',
      'daily_usage_times': 'Daily Usage Times',
      'times': 'Times',
      'first_dose_time': 'First Dose Time',
      'start_date': 'Start Date',
      'usage_days_count': 'Usage Days Count',
      'day': 'Day',
      'save_medicine': 'Save Medicine',
      'select_time': 'Select Time',
      'select_date': 'Select Date',
      'select_time_date': 'Please select time and date',
      'medicine_saved_success': 'Medicine saved successfully',
      'save_medicine_failed': 'Failed to save medicine',
      'medicine_added_to_list': 'Medicine added to list',
      'required': 'Required',
      'health_value': 'Health Value',
      'patient_records': 'Patient Records',
      'failed_load_patient_data': 'Failed to load patient data',
      'failed_load_health_data': 'Failed to load health data',
      'data_updated_success': 'Data updated successfully',
      'failed_update_data': 'Failed to update data',
      'try_again': 'Try Again',
      'no_patient_data': 'No patient data available',
      'reload': 'Reload',
      'no_data_today': 'No data available for today',
      'entered_at': 'Entered at',
      'failed_delete_value': 'Failed to delete value',
      'medications_list': 'Medications List',
      'todays_medications': "Today's Medications",
      'health_status': 'Health Status',
      'blood_pressure': 'Blood Pressure',
      'blood_sugar': 'Blood Sugar',
      'recent_activity': 'Recent Activity',
      'last_measurement': 'Last Measurement',
      'normal': 'Normal',
      'measured_on': 'Measured on',
      'quick_actions': 'Quick Actions',
      'add_blood_pressure': 'Add BP',
      'add_blood_sugar': 'Add Sugar',
      'type_message_hint': 'Type your message...',
      'typing': 'Typing...',
      'error_sending_message':
          'Sorry, I encountered an error. Please try again.',
      'mmhg': 'mmHg',
      'systolic': 'Systolic',
      'diastolic': 'Diastolic',
      'low': 'Low',
      'elevated': 'Elevated',
      'high': 'High',
      'very_high': 'Very High',
      'pressure_saved_success': 'Blood pressure saved successfully',
      'failed_save_measurement': 'Failed to save measurement',
      'no_medications': 'No medication today',
      'filtered_list': 'Filtered List',
      'selected_date': 'Selected Date',
      'total_reminders': 'Total Reminders',
      'filtered_reminders': 'Filtered Reminders',
      'no_reminders_for_date': 'No reminders for selected date',
      'reminder_id': 'Reminder ID',
      'time': 'Time',
      'no_medications_for_date': 'No medications for selected date',
      'change_date': 'Change date',
      'dose_times': 'Dose Times:',
      'blood_sugar_value': 'Blood sugar value',
      'mgdl': 'mg/dL',
      'fasting': 'Fasting',
      'prediabetes': 'Prediabetes',
      'slightly_high': 'Slightly high',
      'unknown': 'Unknown',
      'sugar_saved_success': 'Sugar measurement saved successfully',
      'treatment_pathway': 'Treatment Pathway',
      'treatment_plan': 'Treatment Plan',
      'error_occurred': 'An error occurred',
      'save': 'Save',
      'patients_records': 'Patients Records',
      'no_patients': 'No patients found',
      'add_patient': 'Add Patient',
      'refresh': 'Refresh',
      'post': 'Post',
      'comments': 'Comments',
      'write_comment': 'Write a comment...',
      'case_details': 'Case Details',
      'state_updated_success': 'State updated successfully',
      'failed_update_state': 'Failed to update state',
      'case_info': 'Case Information',
      'creation_date': 'Creation Date',
      'last_update': 'Last Update',
      'case_number': 'Case Number',
      'clinical_history': 'Clinical History',
      'main_complaint': 'Main Complaint',
      'symptoms': 'Symptoms',
      'medical_history': 'Medical History',
      'surgical_history': 'Surgical History',
      'medication_history': 'Medication History',
      'allergies': 'Allergies',
      'smoking': 'Smoking',
      'clinical_examination': 'Clinical Examination',
      'signs': 'Signs',
      'vital_signs': 'Vital Signs',
      'exam_results': 'Examination Results',
      'diagnosis': 'Diagnosis',
      'not_specified': 'Not specified',
      'my_cases': 'My Cases',
      'patient_info': 'Patient Information',
      'patient_cases': 'Patient Cases',
      'no_cases': 'No cases found',
      'updated_at': 'Updated at',
      'communities': 'Communities',
      'members': 'members',
      'likes': 'likes',
      'member': 'Member',
      'join': 'Join',
      'joining': 'Joining',
      'create_new_post': '✍️ Create New Post',
      'title_optional': 'Title (optional)',
      'write_post_content': 'Write post content...',
      'content_required': 'Content is required!',
      'post_published_success': '✅ Post published successfully',
      'publish': 'Publish',
      'minutes_ago': 'minutes ago',
      'minute_ago': 'minute ago',
      'hours_ago': 'hours ago',
      'hour_ago': 'hour ago',
      'days_ago': 'days ago',
      'day_ago': 'day ago',
      'comment': 'Comment',
      'no_description': 'No description',
      'create_post': 'Create Post',
      'no_posts_yet': 'No posts yet',
      'add_treatment_pathway': 'Add Treatment Pathway',
      'treatment_plan_description': 'Treatment Plan Description',
      'enter_plan_description': 'Please enter the treatment plan description',
      'enter_plan_description_hint': 'Enter treatment plan description',
      'no_medications_added': 'No medications added',
      'add_medication': 'Add Medication',
      'added_medications': 'Added Medications',
      'no_medications_yet': 'No medications added yet',
      'medications_saved_success': 'Medications saved successfully',
      'failed_save_medications': 'Failed to save medications',
      'save_treatment_pathway': 'Save Treatment Pathway',
      'medical_form': 'Medical Form',
      'failed_load_patients': 'Failed to load patients',
      'select_patient_first': 'Please select a patient first',
      'fill_required_fields': 'Please fill all required fields',
      'sending_data_to': 'Sending data to',
      'case_created_success': 'Case created successfully',
      'unknown_error': 'Unknown error',
      'sending_error': 'Sending error',
      'search_patient_by_name_id': 'Search patient by name or ID',
      'select_patient': 'Select patient',
      'selected_patient': 'Selected patient',
      'smoking_status': 'Smoking Status',
      'pressure_temp_pulse': 'Pressure, temperature, pulse...',
      'lab_results_optional': 'Lab results (optional)',
      'fill_this_field': 'Please fill this field',
      'choose_file': 'Choose file',
      'create_account': 'Create Account',
      'choose_from_gallery': 'Choose from Gallery',
      'take_photo': 'Take Photo',
      'enter_valid_name': 'Enter a valid name',
      'enter_email': 'Enter email',
      'invalid_email': 'Invalid email',
      'enter_password': 'Enter password',
      'password_min_length': 'Password must be at least 8 characters',
      'password_mismatch': 'Passwords do not match',
      'select_role': 'Please select a role',
      'full_name': 'Full Name',
      'password': 'Password',
      'confirm_password': 'Confirm Password',
      'role': 'Role',
      'patient': 'Patient',
      'doctor': 'Doctor',
      'already_have_account': 'Already have an account?',
      'login': 'Login',
      'account_creation_error': 'Error occurred during account creation',
      'create_community': 'Create Community',
      'community_name': 'Community Name',
      'description': 'Description',
      'public': 'Public',
      'private': 'Private',
      'community_created': 'Community created successfully!',
      'create': 'Create',
      'echo_image_optional': 'Echo image (optional)',
      'enter_your_info': 'Please enter your information',
      'birth_date': 'Birth Date',
      'enter_birth_date': 'Please enter birth date',
      'invalid_date_format': 'Invalid date format (yyyy-MM-dd)',
      'gender': 'Gender',
      'select_gender': 'Please select gender',
      'male': 'Male',
      'female': 'Female',
      'phone_number': 'Phone Number',
      'enter_phone': 'Please enter phone number',
      'invalid_phone': 'Please enter a valid phone number',
      'chronic_diseases': 'Chronic Diseases',
      'chronic_diseases_example': 'Example: Diabetes, Hypertension',
      'enter_chronic_diseases': 'Please enter chronic diseases or write "None"',
      'save_data': 'Save Data',
      'patient_registered_success':
          'Patient registered successfully. Please login.',
      'registration_failed': 'Registration failed',
      'date_selection_error': 'Date selection error',
      'view_case': "View Case Details",
      "case_not_found": "Case not found",
      "medications": "Medications",
      "error_loading_medications": "Error loading medications",
      "lab_results": "Lab Results",
      "examinations": "Examinations",
      "notes": "Notes",
      "no_posts": "No posts found",
      "no_title": "No title",
      'patient_name': 'Patient Name',
      'add': 'Add',
      'added_patient': 'Added Patient',
      'no_data': 'No data',
      'phone': 'Phone',
      'cases_count': 'Cases Count',
      'confirm_delete_message': 'Are you sure you want to delete your account?',
      "chatbot_title": "Medical Assistant",
      "send": "Send",
      "login_required": "You must log in first",
      "password_length": "Password must be at least 8 characters",
      "forgot_password": "Forgot password?",
      "no_account": "Don't have an account?",
      "sign_up": "Sign Up",
      "doctor_info": "Doctor Information",
      "enter_professional_info": "Please enter your professional information",
      "certificate_file": "Certificate (JPG, PNG, PDF)",
      "tap_to_select_file": "Tap to select file",
      "enter_field": "Please enter {0}",
      "enter_clinic_phone": "Please enter the clinic phone number",
      "upload_certificate": "Please upload the certificate",
      "fill_required_fields_and_attach_certificate":
          "⚠️ Please fill all required fields and attach the certificate",
      "doctor_registered_success":
          "Doctor registered successfully. Please log in.",
      "save_info": "Save Information",
      "edit_community": "Edit Community",
      "type": "Type",
      "community_updated_success": "Community updated successfully",
      "save_changes_success": "Changes saved successfully",
    },
    'ar': {
      'profile': 'الملف الشخصي',
      'status': 'الحالة',
      'active': 'مفعل ✅',
      'pending': 'بانتظار التفعيل ⏳',
      'specialization': 'التخصص',
      'clinic_address': 'عنوان العيادة',
      'clinic_phone': 'هاتف العيادة',
      'verification_status': 'حالة التحقق',
      'edit': 'تعديل',
      'delete_account': 'حذف الحساب',
      'confirm_delete': 'تأكيد الحذف',
      'delete_warning': 'هل أنت متأكد أنك تريد حذف حسابك؟ لا يمكن التراجع.',
      'cancel': 'إلغاء',
      'delete': 'حذف',
      'error': 'حدث خطأ',
      'edit_profile': 'تعديل الملف الشخصي',
      'name': 'الاسم',
      'email': 'البريد الإلكتروني',
      'save_changes': 'حفظ التغييرات',
      "home": "الرئيسية",
      "health_records": "السجلات الصحية",
      "medicines": "الأدوية",
      "community": "المجتمع",
      "smart_assistant": "المساعد الذكي",
      "records": "السجلات",
      "change_language": "تغيير اللغة",
      "logout": "تسجيل الخروج",
      "logout_confirmation": "هل أنت متأكد من أنك تريد تسجيل الخروج؟",
      "confirm": "تأكيد",
      "unknown_user": "مستخدم غير معروف",
      "no_email": "لا يوجد بريد إلكتروني",
      'add_medicine': 'إضافة دواء',
      'medicine_name': 'اسم الدواء',
      'example_amoxicillin': 'مثال: أموكسيسيلين',
      'dosage': 'الجرعة',
      'example_500mg': 'مثال: 500mg',
      'daily_usage_times': 'عدد مرات الاستخدام يومياً',
      'times': 'مرات',
      'first_dose_time': 'وقت الجرعة الأولى',
      'start_date': 'تاريخ البدء',
      'usage_days_count': 'عدد أيام الاستخدام',
      'day': 'يوم',
      'save_medicine': 'حفظ الدواء',
      'select_time': 'اختر الوقت',
      'select_date': 'اختر التاريخ',
      'select_time_date': 'يرجى اختيار الوقت والتاريخ',
      'medicine_saved_success': 'تم حفظ الدواء بنجاح',
      'save_medicine_failed': 'فشل حفظ الدواء',
      'medicine_added_to_list': 'تمت إضافة الدواء إلى القائمة',
      'required': 'مطلوب',
      'health_value': 'القيم الصحية',
      'patient_records': 'سجلات المريض',
      'failed_load_patient_data': 'فشل في تحميل بيانات المريض',
      'failed_load_health_data': 'فشل في تحميل البيانات الصحية',
      'data_updated_success': 'تم تحديث البيانات بنجاح',
      'failed_update_data': 'فشل في تحديث البيانات',
      'try_again': 'إعادة المحاولة',
      'no_patient_data': 'لا توجد بيانات للمريض',
      'reload': 'إعادة تحميل',
      'no_data_today': 'لا توجد بيانات في هذا اليوم',
      'entered_at': 'تم الإدخال:',
      'failed_delete_value': 'فشل في حذف القيمة',
      'medications_list': 'قائمة الأدوية',
      'todays_medications': 'أدوية اليوم',
      'health_status': 'الحالة الصحية',
      'blood_pressure': 'ضغط الدم',
      'blood_sugar': 'سكر الدم',
      'recent_activity': 'النشاط الأخير',
      'last_measurement': 'آخر قياس',
      'normal': 'طبيعي',
      'measured_on': 'تم القياس في',
      'quick_actions': 'إجراءات سريعة',
      'add_blood_pressure': 'إضافة ضغط',
      'add_blood_sugar': 'إضافة سكر',
      'type_message_hint': 'اكتب رسالتك...',
      'typing': 'يكتب الآن...',
      'error_sending_message': 'عذراً، حدث خطأ. يرجى المحاولة مرة أخرى.',
      'mmhg': 'ملم زئبق',
      'systolic': 'الانقباضي',
      'diastolic': 'الانبساطي',
      'low': 'منخفض',
      'elevated': 'مرتفع قليلاً',
      'high': 'مرتفع',
      'very_high': 'مرتفع جداً',
      'pressure_saved_success': 'تم حفظ قياس الضغط بنجاح',
      'failed_save_measurement': 'فشل في حفظ القياس',
      'no_medications': 'لا يوجد أدوية اليوم',
      'filtered_list': 'القائمة بعد الفلترة',
      'selected_date': 'التاريخ المحدد',
      'total_reminders': 'عدد جميع الـ reminders',
      'filtered_reminders': 'عدد الـ reminders بعد الفلترة',
      'no_reminders_for_date': 'لا توجد reminders للتاريخ المحدد',
      'reminder_id': 'Reminder ID',
      'time': 'الوقت',
      'no_medications_for_date': 'لا توجد أدوية للتاريخ المحدد',
      'change_date': 'تغيير التاريخ',
      'dose_times': 'مواعيد الجرعات:',
      'blood_sugar_value': 'قيمة سكر الدم',
      'mgdl': 'ملغم/ديسيلتر',
      'fasting': 'صائم',
      'prediabetes': 'ما قبل السكري',
      'slightly_high': 'مرتفع قليلاً',
      'unknown': 'غير معروف',
      'sugar_saved_success': 'تم حفظ قياس السكر بنجاح',
      'treatment_pathway': 'المسار العلاجي',
      'treatment_plan': 'الخطة العلاجية',
      'error_occurred': 'حدث خطأ',
      'save': 'حفظ',
      'patients_records': 'سجلات المرضى',
      'no_patients': 'لا يوجد مرضى',
      'add_patient': 'إضافة مريض',
      'refresh': 'تحديث',
      'post': 'منشور',
      'comments': 'التعليقات',
      'write_comment': 'اكتب تعليقاً...',
      'case_details': 'تفاصيل الحالة',
      'state_updated_success': 'تم تحديث الحالة بنجاح',
      'failed_update_state': 'فشل في تحديث الحالة',
      'case_info': 'معلومات الحالة',
      'creation_date': 'تاريخ الإنشاء',
      'last_update': 'آخر تحديث',
      'case_number': 'رقم الحالة',
      'clinical_history': 'القصة السريرية',
      'main_complaint': 'الشكاية الرئيسية',
      'symptoms': 'الأعراض',
      'medical_history': 'السوابق المرضية',
      'surgical_history': 'السوابق الجراحية',
      'medication_history': 'السوابق الدوائية',
      'allergies': 'التحسس',
      'smoking': 'التدخين',
      'clinical_examination': 'الفحص السريري',
      'signs': 'العلامات',
      'vital_signs': 'العلامات الحيوية',
      'exam_results': 'نتيجة الفحص السريري',
      'diagnosis': 'التشخيص',
      'not_specified': 'غير محدد',
      'my_cases': 'حالاتي',
      'patient_info': 'معلومات المريض',
      'patient_cases': 'حالات المريض',
      'no_cases': 'لا يوجد حالات',
      'updated_at': 'تم التحديث',
      'communities': 'المجتمعات',
      'members': 'عضو',
      'likes': 'إعجاب',
      'member': 'عضو',
      'join': 'انضمام',
      'joining': 'انضمام إلى',
      'create_new_post': '✍️ إنشاء بوست جديد',
      'title_optional': 'العنوان (اختياري)',
      'write_post_content': 'اكتب محتوى البوست...',
      'content_required': '⚠️ المحتوى مطلوب!',
      'post_published_success': '✅ تم نشر البوست بنجاح',
      'publish': 'نشر',
      'minutes_ago': 'دقائق مضت',
      'minute_ago': 'دقيقة مضت',
      'hours_ago': 'ساعات مضت',
      'hour_ago': 'ساعة مضت',
      'days_ago': 'أيام مضت',
      'day_ago': 'يوم مضت',
      'comment': 'تعليق',
      'no_description': 'لا يوجد وصف',
      'create_post': 'إنشاء منشور',
      'no_posts_yet': 'لا توجد منشورات بعد',
      'add_treatment_pathway': 'إضافة مسار علاجي',
      'treatment_plan_description': 'وصف الخطة العلاجية',
      'enter_plan_description': 'يرجى إدخال وصف الخطة العلاجية',
      'enter_plan_description_hint': 'أدخل وصف الخطة العلاجية',
      'no_medications_added': 'لم يتم إضافة أي دواء',
      'add_medication': 'إضافة دواء',
      'added_medications': 'الأدوية المضافة',
      'no_medications_yet': 'لم يتم إضافة أي دواء بعد',
      'medications_saved_success': 'تم حفظ الأدوية بنجاح',
      'failed_save_medications': 'فشل حفظ الأدوية',
      'save_treatment_pathway': 'حفظ المسار العلاجي',
      'medical_form': 'الاستمارة الطبية',
      'failed_load_patients': 'فشل في جلب المرضى',
      'select_patient_first': 'يرجى اختيار مريض أولاً',
      'fill_required_fields': 'يرجى تعبئة جميع الحقول الإلزامية',
      'sending_data_to': 'جاري إرسال البيانات للمريض',
      'case_created_success': 'تم إنشاء الحالة بنجاح',
      'unknown_error': 'خطأ غير معروف',
      'sending_error': 'خطأ في الإرسال',
      'search_patient_by_name_id': 'ابحث عن مريض بالاسم أو ID',
      'select_patient': 'اختر المريض',
      'selected_patient': 'المريض المختار',
      'smoking_status': 'حالة التدخين',
      'echo_image_optional': 'صورة Echo (اختياري)',
      'pressure_temp_pulse': 'ضغط، حرارة، نبض...',
      'lab_results_optional': 'نتيجة فحص المختبر (اختياري)',
      'fill_this_field': 'يرجى تعبئة هذا الحقل',
      'choose_file': 'اختر ملف',
      'create_account': 'إنشاء حساب',
      'choose_from_gallery': 'اختر من المعرض',
      'take_photo': 'التقط صورة',
      'enter_valid_name': 'أدخل اسماً صحيحاً',
      'enter_email': 'أدخل البريد الإلكتروني',
      'invalid_email': 'البريد غير صالح',
      'enter_password': 'أدخل كلمة المرور',
      'password_min_length': 'كلمة المرور يجب أن تكون 8 أحرف على الأقل',
      'password_mismatch': 'كلمة المرور غير متطابقة',
      'select_role': 'يرجى اختيار الدور',
      'full_name': 'الاسم الكامل',
      'password': 'كلمة المرور',
      'confirm_password': 'تأكيد كلمة المرور',
      'role': 'الدور',
      'patient': 'مريض',
      'doctor': 'طبيب',
      'already_have_account': 'لديك حساب بالفعل؟',
      'login': 'تسجيل الدخول',
      'account_creation_error': 'حدث خطأ أثناء إنشاء الحساب',
      'create_community': 'إنشاء مجتمع',
      'community_name': 'اسم المجتمع',
      'description': 'الوصف',
      'public': 'عام',
      'private': 'خاص',
      'community_created': 'تم إنشاء المجتمع بنجاح!',
      'create': 'إنشاء',
      'enter_your_info': 'الرجاء إدخال معلوماتك',
      'birth_date': 'تاريخ الميلاد',
      'enter_birth_date': 'الرجاء إدخال تاريخ الميلاد',
      'invalid_date_format': 'صيغة التاريخ غير صحيحة (yyyy-MM-dd)',
      'gender': 'الجنس',
      'select_gender': 'الرجاء اختيار الجنس',
      'male': 'ذكر',
      'female': 'أنثى',
      'phone_number': 'رقم الهاتف',
      'enter_phone': 'الرجاء إدخال رقم الهاتف',
      'invalid_phone': 'أدخل رقم هاتف صحيح',
      'chronic_diseases': 'الأمراض المزمنة',
      'chronic_diseases_example': 'مثال: السكري, الضغط',
      'enter_chronic_diseases': 'الرجاء إدخال الأمراض المزمنة أو كتابة لا يوجد',
      'save_data': 'حفظ البيانات',
      'patient_registered_success': 'تم تسجيل المريض بنجاح الرجاء تسجيل الدخول',
      'registration_failed': 'فشل التسجيل',
      'date_selection_error': 'خطأ في اختيار التاريخ',
      "view_case": "عرض تفاصيل الحالة",
      "case_not_found": "لم يتم العثور على الحالة",
      "medications": "الأدوية",
      "error_loading_medications": "حدث خطأ أثناء تحميل الأدوية",
      "lab_results": "نتائج التحاليل",
      "examinations": "الفحوصات",
      "notes": "ملاحظات",
      "no_posts": "لا توجد منشورات",
      "no_title": "بدون عنوان",
      'patient_name': 'اسم المريض',
      'add': 'إضافة',
      'added_patient': 'تمت إضافة المريض',
      'no_data': 'لا توجد بيانات',
      'phone': 'الهاتف',
      'cases_count': 'عدد الحالات',
      'confirm_delete_message': 'هل أنت متأكد من حذف حسابك؟',
      "chatbot_title": "المساعد الطبي",
      "send": "إرسال",
      "login_required": "يجب تسجيل الدخول أولاً",
      "password_length": "كلمة المرور يجب أن تكون 8 أحرف على الأقل",
      "forgot_password": "نسيت كلمة المرور؟",
      "no_account": "لا تملك حساب؟",
      "sign_up": "إنشاء حساب",
      "doctor_info": "معلومات الطبيب",
      "enter_professional_info": "الرجاء إدخال بياناتك المهنية",
      "certificate_file": "الشهادة (JPG, PNG, PDF)",
      "tap_to_select_file": "اضغط لاختيار ملف",
      "enter_field": "الرجاء إدخال {0}",
      "enter_clinic_phone": "الرجاء إدخال رقم العيادة",
      "upload_certificate": "الرجاء رفع الشهادة",
      "fill_required_fields_and_attach_certificate":
          "⚠️ يرجى تعبئة جميع الحقول المطلوبة وإرفاق الشهادة",
      "doctor_registered_success": "تم تسجيل الطبيب بنجاح. الرجاء تسجيل الدخول",
      "save_info": "حفظ البيانات",
      "edit_community": "تعديل المجتمع",
      "type": "النوع",
      "community_updated_success": "تم تحديث المجتمع بنجاح",
      "no_treatment_pathway": "لا يوجد مسار علاجي",
      "save_changes_success": "تم حفظ التغييرات بنجاح",
    },
  };

  String get(String key) {
    return _localizedValues[locale.languageCode]?[key] ??
        _localizedValues['en']![key]!;
  }
}

class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['en', 'ar'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(AppLocalizationsDelegate old) => false;
}
