// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC675d7KFg6C_cPIBVHg9O720YuLpRVHMg',
    appId: '1:710362032071:android:7ec0c41138610b6f051be2',
    messagingSenderId: '710362032071',
    projectId: 'health-bridge-925df',
    storageBucket: 'health-bridge-925df.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrO4nBCYA2ew5s-9o0nbqGUp7FV2X7_1E',
    appId: '1:710362032071:web:c76299d6cca5512d051be2',
    messagingSenderId: '710362032071',
    projectId: 'health-bridge-925df',
    authDomain: 'health-bridge-925df.firebaseapp.com',
    storageBucket: 'health-bridge-925df.firebasestorage.app',
    measurementId: 'G-C7J1ELW6JP',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAseVyrbbshYG9VvZhIk9jop15JICWMB2U',
    appId: '1:710362032071:ios:6f371c195efdc1f0051be2',
    messagingSenderId: '710362032071',
    projectId: 'health-bridge-925df',
    storageBucket: 'health-bridge-925df.firebasestorage.app',
    iosBundleId: 'com.example.healthBridge',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAseVyrbbshYG9VvZhIk9jop15JICWMB2U',
    appId: '1:710362032071:ios:6f371c195efdc1f0051be2',
    messagingSenderId: '710362032071',
    projectId: 'health-bridge-925df',
    storageBucket: 'health-bridge-925df.firebasestorage.app',
    iosBundleId: 'com.example.healthBridge',
  );

}